export const courses = [
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'آموزش برنامه‌نویسی وب با Next.js',
    category: 'فناوری',
    description:
      'یادگیری توسعه وب مدرن با Next.js، React و TypeScript از صفر تا حرفه‌ای.',
    instructor: 'علی رضایی',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    duration: 540,
    price: 450000,
    originalPrice: 900000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مدیریت کسب‌وکارهای کوچک',
    category: 'کسب‌وکار',
    description: 'آشنایی با اصول مدیریت و رشد کسب‌وکارهای کوچک با رویکرد عملی.',
    instructor: 'مریم احمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    duration: 420,
    price: 0,
    originalPrice: 300000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مبانی طراحی گرافیک مدرن',
    category: 'هنر',
    description:
      'شروع طراحی گرافیک با ابزارهای حرفه‌ای مانند Photoshop و Illustrator.',
    instructor: 'سارا محمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    duration: 360,
    price: 200000,
    originalPrice: 400000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'آموزش برنامه‌نویسی وب با Next.js',
    category: 'فناوری',
    description:
      'یادگیری توسعه وب مدرن با Next.js، React و TypeScript از صفر تا حرفه‌ای.',
    instructor: 'علی رضایی',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    duration: 540,
    price: 450000,
    originalPrice: 900000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مدیریت کسب‌وکارهای کوچک',
    category: 'کسب‌وکار',
    description: 'آشنایی با اصول مدیریت و رشد کسب‌وکارهای کوچک با رویکرد عملی.',
    instructor: 'مریم احمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    duration: 420,
    price: 0,
    originalPrice: 300000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مبانی طراحی گرافیک مدرن',
    category: 'هنر',
    description:
      'شروع طراحی گرافیک با ابزارهای حرفه‌ای مانند Photoshop و Illustrator.',
    instructor: 'سارا محمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    duration: 360,
    price: 200000,
    originalPrice: 400000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'آموزش برنامه‌نویسی وب با Next.js',
    category: 'فناوری',
    description:
      'یادگیری توسعه وب مدرن با Next.js، React و TypeScript از صفر تا حرفه‌ای.',
    instructor: 'علی رضایی',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    duration: 540,
    price: 450000,
    originalPrice: 900000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مدیریت کسب‌وکارهای کوچک',
    category: 'کسب‌وکار',
    description: 'آشنایی با اصول مدیریت و رشد کسب‌وکارهای کوچک با رویکرد عملی.',
    instructor: 'مریم احمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    duration: 420,
    price: 0,
    originalPrice: 300000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مبانی طراحی گرافیک مدرن',
    category: 'هنر',
    description:
      'شروع طراحی گرافیک با ابزارهای حرفه‌ای مانند Photoshop و Illustrator.',
    instructor: 'سارا محمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    duration: 360,
    price: 200000,
    originalPrice: 400000,
  },

  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'آموزش برنامه‌نویسی وب با Next.js',
    category: 'فناوری',
    description:
      'یادگیری توسعه وب مدرن با Next.js، React و TypeScript از صفر تا حرفه‌ای.',
    instructor: 'علی رضایی',
    instructorAvatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    duration: 540,
    price: 450000,
    originalPrice: 900000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مدیریت کسب‌وکارهای کوچک',
    category: 'کسب‌وکار',
    description: 'آشنایی با اصول مدیریت و رشد کسب‌وکارهای کوچک با رویکرد عملی.',
    instructor: 'مریم احمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/45.jpg',
    duration: 420,
    price: 0,
    originalPrice: 300000,
  },
  {
    image: '/images/modern-workspace-library-ui.png',
    title: 'مبانی طراحی گرافیک مدرن',
    category: 'هنر',
    description:
      'شروع طراحی گرافیک با ابزارهای حرفه‌ای مانند Photoshop و Illustrator.',
    instructor: 'سارا محمدی',
    instructorAvatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    duration: 360,
    price: 200000,
    originalPrice: 400000,
  },
];

export const courseLesseons = [
  {
    title: 'مقدمه‌ای بر Next.js',
    description: 'آشنایی با ساختار و ویژگی‌های اصلی Next.js',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 120,
    order: 1,
    courseId: 1,
  },
  {
    title: 'ساخت اولین صفحه',
    description: 'ایجاد یک صفحه ساده با استفاده از Next.js',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 2,
  },
  {
    title: 'کار با API Routes',
    description: 'ساخت API در Next.js بدون نیاز به بک‌اند جداگانه',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 240,
    order: 3,
    courseId: 3,
  },

  // دوره 2
  {
    title: 'اصول مدیریت زمان',
    description: 'چگونه کارها را به صورت موثر مدیریت کنیم',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 150,
    order: 1,
    courseId: 4,
  },
  {
    title: 'مدیریت منابع انسانی',
    description: 'چگونه تیم کوچک خود را به بهترین شکل هدایت کنیم',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 5,
  },
  {
    title: 'بازاریابی دیجیتال',
    description: 'استراتژی‌های رشد آنلاین برای کسب‌وکارهای کوچک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 210,
    order: 3,
    courseId: 6,
  },

  // دوره 3
  {
    title: 'مبانی طراحی',
    description: 'آشنایی با اصول پایه‌ای طراحی گرافیک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 120,
    order: 1,
    courseId: 7,
  },
  {
    title: 'کار با Photoshop',
    description: 'ابزارهای مهم فتوشاپ برای طراحی گرافیک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 150,
    order: 2,
    courseId: 8,
  },
  {
    title: 'کار با Illustrator',
    description: 'طراحی وکتور با Adobe Illustrator',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 3,
    courseId: 9,
  },

  // دوره 1
  {
    title: 'مقدمه‌ای بر Next.js',
    description: 'آشنایی با ساختار و ویژگی‌های اصلی Next.js',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 120,
    order: 1,
    courseId: 10,
  },
  {
    title: 'ساخت اولین صفحه',
    description: 'ایجاد یک صفحه ساده با استفاده از Next.js',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 11,
  },
  {
    title: 'کار با API Routes',
    description: 'ساخت API در Next.js بدون نیاز به بک‌اند جداگانه',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 240,
    order: 3,
    courseId: 12,
  },

  // دوره 2
  {
    title: 'اصول مدیریت زمان',
    description: 'چگونه کارها را به صورت موثر مدیریت کنیم',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 150,
    order: 2,
    courseId: 1,
  },
  {
    title: 'مدیریت منابع انسانی',
    description: 'چگونه تیم کوچک خود را به بهترین شکل هدایت کنیم',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 2,
  },
  {
    title: 'بازاریابی دیجیتال',
    description: 'استراتژی‌های رشد آنلاین برای کسب‌وکارهای کوچک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 210,
    order: 2,
    courseId: 3,
  },

  // دوره 3
  {
    title: 'مبانی طراحی',
    description: 'آشنایی با اصول پایه‌ای طراحی گرافیک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 120,
    order: 2,
    courseId: 4,
  },
  {
    title: 'کار با Photoshop',
    description: 'ابزارهای مهم فتوشاپ برای طراحی گرافیک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 150,
    order: 2,
    courseId: 5,
  },
  {
    title: 'کار با Illustrator',
    description: 'طراحی وکتور با Adobe Illustrator',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 6,
  },

  // دوره 1
  {
    title: 'مقدمه‌ای بر Next.js',
    description: 'آشنایی با ساختار و ویژگی‌های اصلی Next.js',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 120,
    order: 2,
    courseId: 7,
  },
  {
    title: 'ساخت اولین صفحه',
    description: 'ایجاد یک صفحه ساده با استفاده از Next.js',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 8,
  },
  {
    title: 'کار با API Routes',
    description: 'ساخت API در Next.js بدون نیاز به بک‌اند جداگانه',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 240,
    order: 2,
    courseId: 9,
  },

  // دوره 2
  {
    title: 'اصول مدیریت زمان',
    description: 'چگونه کارها را به صورت موثر مدیریت کنیم',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 150,
    order: 2,
    courseId: 10,
  },
  {
    title: 'مدیریت منابع انسانی',
    description: 'چگونه تیم کوچک خود را به بهترین شکل هدایت کنیم',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 180,
    order: 2,
    courseId: 11,
  },
  {
    title: 'بازاریابی دیجیتال',
    description: 'استراتژی‌های رشد آنلاین برای کسب‌وکارهای کوچک',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    duration: 210,
    order: 2,
    courseId: 12,
  },
];
